(function($){var api=wp.customize;AstTypography={init:function(){AstTypography._initFonts();},_initFonts:function()
{$('.customize-control-ast-font-family select').each(function(e){if('undefined'!=typeof astra.customizer){var fonts=astra.customizer.settings.google_fonts;var optionName=$(this).data('name');$(this).html(fonts);$("select[data-name='"+optionName+"'] option[value='inherit']").text($(this).data('inherit'));var font_val=$(this).data('value');$(this).val(font_val);}});$('.customize-control-ast-font-family select').each(AstTypography._initFont);$('.customize-control-ast-font-family select, .customize-control-ast-font-variant select').selectWoo();$('.customize-control-ast-font-variant select').on('select2:unselecting',function(e){var variantSelect=$(this).data('customize-setting-link'),unselectedValue=e.params.args.data.id||'';if(unselectedValue){$(this).find('option[value="'+e.params.args.data.id+'"]').removeAttr('selected');if(null===$(this).val()){api(variantSelect).set('');}}});},_initFont:function()
{var select=$(this),link=select.data('customize-setting-link'),weight=select.data('connected-control'),variant=select.data('connected-variant');if('undefined'!=typeof weight){api(link).bind(AstTypography._fontSelectChange);AstTypography._setFontWeightOptions.apply(api(link),[true]);}
if('undefined'!=typeof variant){api(link).bind(AstTypography._fontSelectChange);AstTypography._setFontVarianttOptions.apply(api(link),[true]);}},_fontSelectChange:function()
{var fontSelect=api.control(this.id).container.find('select'),variants=fontSelect.data('connected-variant');AstTypography._setFontWeightOptions.apply(this,[false]);if('undefined'!=typeof variants){AstTypography._setFontVarianttOptions.apply(this,[false]);}},_cleanGoogleFonts:function(fontValue)
{if(!fontValue.includes(','))return fontValue;var splitFont=fontValue.split(',');var pattern=new RegExp("'",'gi');var googleFontValue=splitFont[0].replace(pattern,'');if('undefined'!=typeof AstFontFamilies.google[googleFontValue]){fontValue=googleFontValue;}
return fontValue;},_getWeightObject:function(fontValue)
{var weightObject=['400','600'];if(fontValue=='inherit'){weightObject=['100','200','300','400','500','600','700','800','900'];}else if('undefined'!=typeof AstFontFamilies.system[fontValue]){weightObject=AstFontFamilies.system[fontValue].weights;}else if('undefined'!=typeof AstFontFamilies.google[fontValue]){weightObject=AstFontFamilies.google[fontValue][0];weightObject=Object.keys(weightObject).map(function(k){return weightObject[k];});}else if('undefined'!=typeof AstFontFamilies.custom[fontValue]){weightObject=AstFontFamilies.custom[fontValue].weights;}
return weightObject;},_setFontWeightOptions:function(init)
{var i=0,fontSelect=api.control(this.id).container.find('select'),fontValue=this(),selected='',weightKey=fontSelect.data('connected-control'),inherit=fontSelect.data('inherit'),weightSelect=api.control(weightKey).container.find('select'),currentWeightTitle=weightSelect.data('inherit'),weightValue=init?weightSelect.val():'400',inheritWeightObject=['inherit'],weightObject=['400','600'],weightOptions='',weightMap=astraTypo;if(fontValue=='inherit'){weightValue=init?weightSelect.val():'inherit';}
var fontValue=AstTypography._cleanGoogleFonts(fontValue);var weightObject=AstTypography._getWeightObject(fontValue);weightObject=$.merge(inheritWeightObject,weightObject)
weightMap['inherit']=currentWeightTitle;for(;i<weightObject.length;i++){if(0===i&&-1===$.inArray(weightValue,weightObject)){weightValue=weightObject[0];selected=' selected="selected"';}else{selected=weightObject[i]==weightValue?' selected="selected"':'';}
if(!weightObject[i].includes("italic")){weightOptions+='<option value="'+weightObject[i]+'"'+selected+'>'+weightMap[weightObject[i]]+'</option>';}}
weightSelect.html(weightOptions);if(!init){api(weightKey).set('');api(weightKey).set(weightValue);}},_setFontVarianttOptions:function(init)
{var i=0,fontSelect=api.control(this.id).container.find('select'),fontValue=this(),selected='',variants=fontSelect.data('connected-variant'),inherit=fontSelect.data('inherit'),variantSelect=api.control(variants).container.find('select'),variantSavedField=api.control(variants).container.find('.ast-font-variant-hidden-value'),weightValue='',weightOptions='',currentWeightTitle=variantSelect.data('inherit'),weightMap=astraTypo;var variantArray=variantSavedField.val().split(',');var selectedOptionGroup=fontSelect.find('option[value="'+fontSelect.val()+'"]').closest('optgroup').attr('label')||'';if('Google'==selectedOptionGroup){variantSelect.parent().removeClass('ast-hide');}else{variantSelect.parent().addClass('ast-hide');}
var fontValue=AstTypography._cleanGoogleFonts(fontValue);var weightObject=AstTypography._getWeightObject(fontValue);weightMap['inherit']=currentWeightTitle;for(var i=0;i<weightObject.length;i++){for(var e=0;e<variantArray.length;e++){if(weightObject[i]===variantArray[e]){weightValue=weightObject[i];selected=' selected="selected"';}else{selected=(weightObject[i]==weightValue)?' selected="selected"':'';}}
weightOptions+='<option value="'+weightObject[i]+'"'+selected+'>'+weightMap[weightObject[i]]+'</option>';}
variantSelect.html(weightOptions);if(!init){api(variants).set('');}},};$(function(){AstTypography.init();});})(jQuery);